version: "3.2"

services:
  postgres_db:
    image: "postgres:16.2"
    container_name: postgres_db
    user: root
    hostname: "postgres_db"
    environment:
      POSTGRES_USER: "ala"
      POSTGRES_PASSWORD: "1234@Pass"
    ports:
      - "5432:5432"
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: on-failure
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ala@ala.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - postgres_db


